# Generated by Django 3.1.6 on 2021-02-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_group_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.group'),
        ),
    ]
