# Generated by Django 3.1.6 on 2021-02-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.IntegerField(choices=[(1, 'English'), (2, 'Farsi')])),
                ('name', models.CharField(max_length=50)),
                ('reading', models.IntegerField()),
                ('writing', models.IntegerField()),
                ('listening', models.IntegerField()),
                ('speaking', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
