# Generated by Django 3.1.6 on 2021-02-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_languageskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.IntegerField(choices=[(1, 'English'), (2, 'Farsi')])),
                ('title', models.CharField(max_length=150)),
                ('begin_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
