# Generated by Django 3.1.6 on 2021-02-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
