# Generated by Django 3.1.6 on 2021-02-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20210213_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
