# Generated by Django 3.1.6 on 2021-02-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_education_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='quote',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
