# Generated by Django 3.1.6 on 2021-02-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_information_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
