# Generated by Django 3.1.6 on 2021-02-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20210213_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
