# Generated by Django 3.1.6 on 2021-02-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_education_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='skills',
            field=models.ManyToManyField(blank=True, to='resume.Skill'),
        ),
    ]
