# Generated by Django 3.1.6 on 2021-02-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_auto_20210215_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
