# Generated by Django 3.1.6 on 2022-10-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_auto_20210215_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
